### ISSUE TITLE
Implementation of hydrogen-bond-like interaction (PDNS)

### ISSUE THREAD

**Issue by MasatakaYm** [yutakasi634/OpenCafeMol#28]
The hydrogen-bond-like interaction (PDNS) [T. Niina et al (2017) PLoS. Comp. Biol.] is now widely used for the CG simulations of the nucleosome system and other DNA-binding proteins. Thus, implementing PDNS will widen the application of OpenAICG2+. In this issue, I would like to request the implementation of PDNS and show the prototype code snippet for implementing PDNS.

### Potential function of PDNS
The potential energy function is defined by
```
U(r, theta, phi) = k*f(r)*g(theta)*g(phi)

where,
   f(r)   = exp(-(r-r0)^2 / 2signam^2)
   g(phi) = 1                              ...         |phi - phi0| <  delta
            1 - cos^2(pi(phi-phi0)/2delta) ... delta < |phi - phi0| < 2delta
            0                              ... otherwise

//  PC          S5'
//    o         o--o B
//    A\ P   D /
// vP | o --> o
//    |/     `-\ 
//    o    phi  o--o B
//  PN          S3'
```
Here,
- `k` is the energy parameter that controls the hydrogen bond strength
- `r` is the distance between the Cα bead of the HB-forming residue and the DNA phosphate
- `theta` is an angle formed by the vector from the neighboring amino acid residue at the N-term side (`PN`) to the amino acid residue at the C-term side (`PC`) (`vP` in the above figure) and the vector from Cα bead on protein to DNA phosphate
- `phi` is the angle formed by the vector from protein to DNA phosphate (Cα→Phos) and the vector from phosphate to sugar bead in the same nucleotide (Phos→S3').

### Input file
Following Mjolnir, a toml input file can be written as follows:
```toml
[[forcefields.global]]
interaction = "PDNS"
potential   = "PDNS"
sigma = 1.0  # angstrom
delta = 0.17453 # radian (= 10 degree)
parameters  = [
{index =    2, S3 = 1, kind = "DNA"},
{index =    5, S3 = 4, kind = "DNA"},
# ...
{index = 1000, kind = "Protein", PN =  999, PC = 1001, k = 1.2, r0 = 5.0, theta0 = 100.0, phi0 = 130.0},
{index = 1023, kind = "Protein", PN = 1022, PC = 1024, k = 1.2, r0 = 6.0, theta0 = 110.0, phi0 = 120.0},
# ...
]
```
Note that OpenAICG2+ needs to set up all possible combinations between protein bead groups and DNA bead groups after loading the input file.

### Prototype for implementing potential function
The below shows the code snippet of the potential function. Here, I assume that `Cα_Cter = p1 (x1, y1, z1)`,  `Cα = p2 (x2, y2, z2)`, `Cα_Nter = p3 (x3, y3, z3)`, `Phos = p4 (x4, y4, z4)`, `S3 = p5 (x5, y5, z5)`.

```
std::string potential_formula = fmt::format(
    "k * f_r * g_theta * g_phi;"
    "f_r       = exp(-dr^2/ (2*sigma*sigma));"
    "g_theta   = max(g1*rect0t, rect1t);"
    "g_phi     = max(g2*rect0p, rect1p);"
    "rect0t    = step(pi   + dtheta) * step(pi   - dtheta);"  // 1 when -pi   < dt < pi  , else 0
    "rect1t    = step(pi/2 + dtheta) * step(pi/2 - dtheta);"  // 1 when -pi/2 < dt < pi/2, else 0
    "rect0p    = step(pi   + dphi)   * step(pi   - dphi);"    // 1 when -pi   < dt < pi  , else 0
    "rect1p    = step(pi/2 + dphi)   * step(pi/2 - dphi);"    // 1 when -pi/2 < dt < pi/2, else 0
    "g1        = 1 - cos(dtheta)^2;"
    "g2        = 1 - cos(dphi)^2;"
    "dr        = distance(p2, p4) - r0;"
    "dtheta    = K * (theta - theta0);"
    "dphi      = K * (phi   - phi0);"
    "K         = pi/(2*delta);"
    "phi       = angle(p2, p4, p5);"
    "theta     = acos(cos_theta);"
    "cos_theta = dot_PNC/(norm_CANC*norm_CAP);"
    "norm_CANC = sqrt((x1-x3)^2 + (y1-y3)^2 + (z1-z3)^2);" // vec_CANC = (x1 - x3, y1 - y3, z1 - z3)
    "norm_CAP  = sqrt((x4-x2)^2 + (y4-y2)^2 + (z4-z2)^2);" // vec_CAP  = (x4 - x2, y4 - y2, z4 - z2)
    "dot_PNC   = (x1-x3)*(x4-x2) + (y1-y3)*(y4-y2) + (z1-z3)*(z4-z2);"
    "pi        = 3.1415926535897932385;"
);
```
I find that it is difficult to define `theta` by using the `angle` function; therefore, I naively calculated the angle from the dot product using the absolute positions of beads (x1, x2, .... z5). 

In order to implement the PDNS potential function, we have to use `CustomCompoundBondForce` rather than `CustomHbondForce` because `CustomHbondForce` cannot treat the absolute positions of beads (https://github.com/openmm/openmm/issues/3642).
